services:
  - type: web
    name: doom-thumbnails
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --worker-class gthread --threads 4 "app:create_app()"
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: DOOM_DRIVE_PARENT_FOLDER_ID
        sync: false
      - key: APP_PASSWORD
        sync: false
      - key: BRAVE_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: NO_BROWSER
        value: "1"
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_DEFAULT_REGION
        value: "us-east-1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"

  - type: web
    name: doom-format
    runtime: node
    rootDir: format-app
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false

